### ISSUE TITLE
How do I print a hash as a table?

### ISSUE THREAD

**Issue by qubitrenegade** [arches/table_print#76]
Hello,

The README doesn't seem to provide a way to print a hash as a table, though it does seem to indicate this library is capable of doing so.

How would one go about printing a hash as a table?

Printing a regular hash does not seem to work as it just prints a bunch of nonsense.  What I'm really trying to do is parse a JSON string and print that as a table, however, this provides the error:

`gem/ruby/2.3.0/gems/table_print-1.5.6/lib/table_print/fingerprinter.rb:44:in `clear': can't modify frozen String (RuntimeError)`

Here's the code I'm trying:

```
require 'table_print'

my_hash = {
  foo: 'bar',
  biz: 'baz'
}
tp my_hash

require 'json'
my_json = '{ "foo": "bar", "biz": "baz" }'
my_json_as_hash = JSON.parse my_json
tp my_json_as_hash
```

This prints:

```
UNIQ           | COMPACT        | TO_H           | BSEARCH_INDEX  | BSEARCH        | SORT           | SELECT         | REJECT         | COLLECT        | MAP            | ANY?           | REVERSE_EACH   | TAKE_WHILE     | DROP_WHILE     | CLEAR          | REVERSE        | EMPTY? | INSPECT | LENGTH | SIZE | EACH           | TO_ARY         | TO_A           | TO_S | HASH                | FROZEN? | EACH_INDEX     | KEEP_IF        | DELETE_IF      | TRANSPOSE
---------------|----------------|----------------|----------------|----------------|----------------|----------------|----------------|----------------|----------------|----------------|----------------|----------------|----------------|----------------|----------------|--------|---------|--------|------|----------------|----------------|----------------|------|---------------------|---------|----------------|----------------|----------------|---------------
Method Missing | Method Missing | Method Missing | Method Missing | Method Missing | Method Missing | Method Missing | Method Missing | Method Missing | Method Missing | Method Missing | Method Missing | Method Missing | Method Missing | Method Missing | Method Missing | false  | :foo    | 3      | 3    | Method Missing | Method Missing | Method Missing | foo  | 3206                | true    | Method Missing | Method Missing | Method Missing | Method Missing
Method Missing | Method Missing | Method Missing | Method Missing | Method Missing | Method Missing | Method Missing | Method Missing | Method Missing | Method Missing | Method Missing | Method Missing | Method Missing | Method Missing |                |                | true   | ""      | 0      | 0    | Method Missing | Method Missing | Method Missing |      | 2095166142864889309 | false   | Method Missing | Method Missing | Method Missing | Method Missing
Method Missing | Method Missing | Method Missing | Method Missing | Method Missing | Method Missing | Method Missing | Method Missing | Method Missing | Method Missing | Method Missing | Method Missing | Method Missing | Method Missing | Method Missing | Method Missing | false  | :biz    | 3      | 3    | Method Missing | Method Missing | Method Missing | biz  | 3207                | true    | Method Missing | Method Missing | Method Missing | Method Missing
Method Missing | Method Missing | Method Missing | Method Missing | Method Missing | Method Missing | Method Missing | Method Missing | Method Missing | Method Missing | Method Missing | Method Missing | Method Missing | Method Missing |                |                | true   | ""      | 0      | 0    | Method Missing | Method Missing | Method Missing |      | 2095166142864889309 | false   | Method Missing | Method Missing | Method Missing | Method Missing
/home/charterlab.com/jaykroyd/.chefdk/gem/ruby/2.3.0/gems/table_print-1.5.6/lib/table_print/fingerprinter.rb:44:in `clear': can't modify frozen String (RuntimeError)
        from /home/me/.gem/ruby/2.3.0/gems/table_print-1.5.6/lib/table_print/fingerprinter.rb:44:in `block in populate_row'
        from /home/me/.gem/ruby/2.3.0/gems/table_print-1.5.6/lib/table_print/fingerprinter.rb:35:in `each'
        from /home/me/.gem/ruby/2.3.0/gems/table_print-1.5.6/lib/table_print/fingerprinter.rb:35:in `populate_row'
        from /home/me/.gem/ruby/2.3.0/gems/table_print-1.5.6/lib/table_print/fingerprinter.rb:19:in `block in hash_to_rows'
        from /home/me/.gem/ruby/2.3.0/gems/table_print-1.5.6/lib/table_print/fingerprinter.rb:18:in `each'
        from /home/me/.gem/ruby/2.3.0/gems/table_print-1.5.6/lib/table_print/fingerprinter.rb:18:in `hash_to_rows'
        from /home/me/.gem/ruby/2.3.0/gems/table_print-1.5.6/lib/table_print/fingerprinter.rb:9:in `lift'
        from /home/me/.gem/ruby/2.3.0/gems/table_print-1.5.6/lib/table_print.rb:41:in `block in table_print'
        from /home/me/.gem/ruby/2.3.0/gems/table_print-1.5.6/lib/table_print.rb:40:in `each'
        from /home/me/.gem/ruby/2.3.0/gems/table_print-1.5.6/lib/table_print.rb:40:in `table_print'
        from /home/me/.gem/ruby/2.3.0/gems/table_print-1.5.6/lib/table_print.rb:73:in `tp'
        from test.rb:12:in `<main>'
```

What am I doing wrong here?  Or is table_printer not able to print hashes?

Thanks!

**Comment by arches** [comment]
table_print expects an array of data, if you want to print a single hash wrap it in square brackets:

```
> my_hash = {foo: 'bar', biz: 'baz'}
=> {:foo=>"bar", :biz=>"baz"}

> tp [my_hash]
FOO | BIZ
----|----
bar | baz
```

**Comment by qubitrenegade** [comment]
omg, that's entirely too easy!

Thanks!
