### ISSUE TITLE
Bug Report: NoMethodError (undefined method `include?' for 0.001695337:Float)

### ISSUE THREAD

**Issue by julienemo** [arches/table_print#84]
**Description**
When launching `tp User.all` (or other use case) in `rails console`, expected results are followed by this error :point_down: 

![tp_bug](https://user-images.githubusercontent.com/29869362/84599577-488e9f80-ae73-11ea-88a6-122ed5847458.png)

This error in text:
```
Traceback (most recent call last):
       16: from /home/julie/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/railties-6.0.3.1/lib/rails/commands/console/console_command.rb:19:in `start'
       15: from /home/julie/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/railties-6.0.3.1/lib/rails/commands/console/console_command.rb:70:in `start'
       14: from /home/julie/.rbenv/versions/2.7.1/lib/ruby/2.7.0/irb.rb:399:in `start'
       13: from /home/julie/.rbenv/versions/2.7.1/lib/ruby/2.7.0/irb.rb:470:in `run'
       12: from /home/julie/.rbenv/versions/2.7.1/lib/ruby/2.7.0/irb.rb:470:in `catch'
       11: from /home/julie/.rbenv/versions/2.7.1/lib/ruby/2.7.0/irb.rb:471:in `block in run'
       10: from /home/julie/.rbenv/versions/2.7.1/lib/ruby/2.7.0/irb.rb:536:in `eval_input'
        9: from /home/julie/.rbenv/versions/2.7.1/lib/ruby/2.7.0/irb/ruby-lex.rb:134:in `each_top_level_statement'
        8: from /home/julie/.rbenv/versions/2.7.1/lib/ruby/2.7.0/irb/ruby-lex.rb:134:in `catch'
        7: from /home/julie/.rbenv/versions/2.7.1/lib/ruby/2.7.0/irb/ruby-lex.rb:135:in `block in each_top_level_statement'
        6: from /home/julie/.rbenv/versions/2.7.1/lib/ruby/2.7.0/irb/ruby-lex.rb:135:in `loop'
        5: from /home/julie/.rbenv/versions/2.7.1/lib/ruby/2.7.0/irb/ruby-lex.rb:150:in `block (2 levels) in each_top_level_statement'
        4: from /home/julie/.rbenv/versions/2.7.1/lib/ruby/2.7.0/irb.rb:537:in `block in eval_input'
        3: from /home/julie/.rbenv/versions/2.7.1/lib/ruby/2.7.0/irb.rb:695:in `signal_status'
        2: from /home/julie/.rbenv/versions/2.7.1/lib/ruby/2.7.0/irb.rb:541:in `block (2 levels) in eval_input'
        1: from /home/julie/.rbenv/versions/2.7.1/lib/ruby/2.7.0/irb.rb:742:in `output_value'
NoMethodError (undefined method `include?' for 0.001695337:Float)
Maybe IRB bug!
```

**Reproduction**
1. Install table_print
2. go to `rails console`
3. use normally (`tp User.all`)
4. The error appears after printed table

**Expected behavior**
Not having this error

**Additional context**
I encountered this error with ruby 2.7.1 + rails 6.0.3, 

ruby 2.6.6 + rails 6.0.0 has no such error

ruby 2.7.1 + rails 6.0.0 does have this error

This might be a compatibility issue with ruby 2.7

**Comment by julienemo** [comment]
PR opened

https://github.com/arches/table_print/pull/85
